### ISSUE TITLE
Duplicate symbols when compiling pynio from source using Python 3.7.4

### ISSUE THREAD

**Issue by wjcapehart** [NCAR/pynio#37]
Hello All:

I’m jumping into the migration from NCL into the python realm and am having difficulty getting started with pyNIO and pyNGL.

My primary program manager has been homebrew and my gcc compiler is 9.2.0.  I am working with python 3.7.4 as my main default distro from homebrew and to date, it’s worked well and pip3 doesn’t create any major conflicts.  But pip’s version of pyNIO are pyNGL are out of date (2006).  

(Because of other projects I would prefer _not_ to work through the conda manager due to previous [recent] extreme difficulties with conda with some packages that I need for other projects.  Also I’d like a consistent development platform between my Mac and our larger department UNIX fleet since I have to manage both but do not have the r€$ouR¢e$ or time to do so).

I had luck getting pyNIO and pyNGL working with python 3.6.8

However.

In trying to bring pyNIO and pyNGL up and running with python 3.7.4, I’ve been getting “duplicate symbol” errors crashing the builds (_NCLnoPrintElem w/ pyNIO, and  _pcmp04_ w/ pyNGL). 

The output from the command ...

python3 ./setup.py  install

... is in the gist link below.

https://gist.github.com/wjcapehart/d44f5618b5baa613cd5be4d328cdfa01

Please advise.
Bill Capehart
SD Mines

**Comment by DylanModesitt** [comment]
Were you ever able to resolve this?

**Comment by wjcapehart** [comment]
Hi Dylan.  I had to table this due to other issues.  I have simply used the pip install instead.
